name: "figma2svg"
description: "Export Figma icons"
inputs:
  token:
    description: "A Figma Personal Access Token"
    required: true
  id:
    description: "The Figma project ID"
    required: true
  output:
    description: "The output directory"
    default: "./build"
  keep_directory:
    description: "Keep the directory structure"
    default: false
runs:
  using: "node16"
  main: "dist/main.js"
